name: Firmware Quality Check

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          pip install platformio

      - name: Compile firmware
        working-directory: ./firmware
        run: |
          platformio run

      - name: Format check (clang-format style)
        run: |
          sudo apt-get install clang-format -y
          find firmware/src_template -name "*.cpp" -o -name "*.h" | xargs clang-format -n || \
            (echo "Formatting errors found!" && exit 1)
            
